### ISSUE TITLE
Use correct attr_android:inputType for TextView

### ISSUE THREAD

**Issue by DMyachin** [torgash-ivanblch/DasPoint#3]
http://developer.android.com/intl/ru/guide/topics/ui/controls/text.html
http://developer.android.com/intl/ru/reference/android/widget/TextView.html#attr_android:inputType
textCapSentences — default
textMultiLine — default
textLongMessage — default
textAutoCorrect — optional
textAutoComplete — optional

**Comment by torgash-ivanblch** [comment]
Done, thank you
